#!/usr/bin/env bash

set -e

terraform fmt
venv/bin/ruff check --fix

cd infra/staging
terraform apply -auto-approve
export API_ENDPOINT=$(terraform output api_endpoint | tr -d '"')
export AGENT_ID=$(terraform output agent_id | tr -d '"')
export AGENT_ALIAS_ID=$(terraform output agent_alias_id | tr -d '"')
cd -

export TABLE_NAME=fact-checker-results-staging
export QUEUE_NAME=fact-checker-queue-staging
venv/bin/pytest --snapshot-update -s

# Add changes to git
git add .
